POST http://localhost:5000/bookmarks/add HTTP/1.1
content-type: application/json

{
    "title": "React & Axios",
    "url": "http://zetcode.com/javascript/axios/",
    "tag": "React Axios",
    "date": "2020-04-30T21:19:15.187Z"
}