export const GET_BOOKMARKS = 'GET_BOOKMARKS';
export const REMOVE_BOOKMARKS = 'REMOVE_BOOKMARKS';
export const ADD_BOOKMARKS = 'ADD_BOOKMARKS';
export const EDIT_BOOKMARKS = 'EDIT_BOOKMARKS';
export const SEARCH_BOOKMARKS = 'SEARCH_BOOKMARKS';
export const ADD_TAGS = 'ADD_TAGS';
export const GET_TAGS = 'GET_TAGS';